# Generated by Django 5.1 on 2024-08-28 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'db_table': 'members',
            },
        ),
        migrations.CreateModel(
            name='MemberRelationshipModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation_type', models.SmallIntegerField(choices=[(1, 'PARENT'), (2, 'CHILD'), (3, 'SIBLING'), (4, 'SPOUSE')])),
                ('member1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_from', to='family_app.membermodel')),
                ('member2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_to', to='family_app.membermodel')),
            ],
            options={
                'verbose_name': 'Member Relations',
                'verbose_name_plural': 'Member Relations',
                'db_table': 'member_relations',
                'unique_together': {('member1', 'member2')},
            },
        ),
    ]
